### ISSUE TITLE
Settings applied on PC do not reflect on phone

### ISSUE THREAD

**Issue by aleksandarmomic** [VueTorrent/vuetorrent-backend#63] opened 2024-10-15 19:18 UTC
So if I understood correctly, the purpose of backend is to have unified settings across devices but I am having different settings on each device. In logs I can clearly see that when I save my settings on PC, PUT request is called and data.json is updated. But after that if I open vuetorrent on my phone, the settings are not updated. For example: I was switching to the Legacy dark theme on my PC, and when I open vuetorrent on my phone, the redesigned theme is selected and used.

**Comment by Larsluph** [comment] 2024-10-15 20:48
Do you have bypass configured or not?

We already have an issue going one that prevents sync if the user isn't authenticated on app launch.

A simple refresh after login should fix the issue temporarily.

**Comment by Larsluph** [comment] 2024-10-16 22:25
You can allow certain IP addresses on qBittorrent that will bypass the authentication step in the webui settings.

If refreshing fixes it, it is indeed a duplicate of VueTorrent/VueTorrent#1918

**Closed by Larsluph** 2024-10-16 22:25 UTC
